name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # ⚠ cambia si tu rama principal se llama diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Obtener el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node (versión estable para Astro)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci --no-optional

      # 4️⃣ Construir proyecto Astro
      - name: Build Astro project
        run: npm run build

      # 5️⃣ Desplegar a GitHub Pages usando gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
